const brands = [
  { value: "any", text: "Любой бренд" },
  { value: "audi", text: "Audi" },
  { value: "bmw", text: "BMW" },
  { value: "chevrolet", text: "Chevrolet" },
  { value: "daewoo", text: "Daewoo" },
  { value: "ford", text: "Ford" },
  { value: "honda", text: "Honda" },
  { value: "hyndai", text: "Hyundai" },
  { value: "kia", text: "Kia" },
  { value: "lexus", text: "Lexus" },
  { value: "mazda", text: "Mazda" },
  { value: "mers", text: "Mercedes-Benz" },
  { value: "mitsubishi", text: "Mitsubishi" },
  { value: "nissan", text: "Nissan" },
  { value: "opel", text: "Opel" },
  { value: "renault", text: "Renault" },
  { value: "subaru", text: "Subaru" },
  { value: "toyota", text: "Toyota" },
  { value: "volkswagen", text: "Volkswagen" },
];
const models = {
  audi: [
    { value: "100", text: "100" },
    { value: "80", text: "80" },
    { value: "90", text: "90" },
    { value: "a3", text: "A3" },
    { value: "a4", text: "A4" },
    { value: "a4-allroad", text: "A4 allroad" },
    { value: "a5", text: "A5" },
    { value: "a6", text: "A6" },
    { value: "a6-allroad", text: "A6 allroad" },
    { value: "a7", text: "A7" },
    { value: "a8", text: "A8" },
    { value: "q3", text: "Q3" },
    { value: "q5", text: "Q5" },
    { value: "q7", text: "Q7" },
    { value: "s4", text: "S4" },
    { value: "tt", text: "TT" },
  ],
  bmw: [
    { value: "3", text: "3 серии" },
    { value: "5", text: "5 серии" },
    { value: "7", text: "7 серии" },
    { value: "x5", text: "X5" },
    { value: "x5m", text: "X5 M" },
    { value: "x6", text: "X6" },
    { value: "x6m", text: "X6 M" },
  ],
  chevrolet: [
    { value: "avalanche", text: "Avalanche" },
    { value: "aveo", text: "Aveo" },
    { value: "camaro", text: "Camaro" },
    { value: "captiva", text: "Captiva" },
    { value: "cobalt", text: "Cobalt" },
    { value: "corvette", text: "Corvette" },
    { value: "cruze", text: "Cruze" },
    { value: "epica", text: "Epica" },
    { value: "lacetti", text: "Lacetti" },
    { value: "lanos", text: "Lanos" },
    { value: "malibu", text: "Malibu" },
    { value: "matiz", text: "Matiz" },
    { value: "niva", text: "Niva" },
    { value: "orlando", text: "Orlando" },
    { value: "spark", text: "Spark" },
    { value: "suburban", text: "Suburban" },
    { value: "tahoe", text: "Tahoe" },
    { value: "tracker", text: "Tracker" },
    { value: "trailblazer", text: "TrailBlazer" },
  ],
  daewoo: [
    { value: "damas", text: "Damas" },
    { value: "espero", text: "Espero" },
    { value: "gentra", text: "Gentra" },
    { value: "kalos", text: "Kalos" },
    { value: "lacetti", text: "Lacetti" },
    { value: "lanos-sens", text: "Lanos (Sens)" },
    { value: "leganza", text: "Leganza" },
    { value: "magnus", text: "Magnus" },
    { value: "matiz", text: "Matiz" },
    { value: "nexia", text: "Nexia" },
    { value: "nubira", text: "Nubira" },
    { value: "winstorm", text: "Winstorm" },
  ],
  ford: [
    { value: "cmax", text: "C-MAX" },
    { value: "eco-sport", text: "EcoSport" },
    { value: "escape", text: "Escape" },
    { value: "explorer", text: "Explorer" },
    { value: "f150", text: "F-150" },
    { value: "fiesta", text: "Fiesta" },
    { value: "focus", text: "Focus" },
    { value: "fusion", text: "Fusion" },
    { value: "galaxy", text: "Galaxy" },
    { value: "kuga", text: "Kuga" },
    { value: "maverick", text: "Maverick" },
    { value: "mondeo", text: "Mondeo" },
    { value: "mustang", text: "Mustang" },
    { value: "smax", text: "S-MAX" },
  ],
  honda: [
    { value: "civic-ferio", text: "Civic Ferio" },
    { value: "cr-v", text: "CR-V" },
    { value: "fit", text: "Fit" },
    { value: "hr-v", text: "HR-V" },
    { value: "inspire", text: "Inspire" },
    { value: "jazz", text: "Jazz" },
    { value: "legend", text: "Legend" },
    { value: "odyssey", text: "Odyssey" },
    { value: "odyssey-north-america", text: "Odyssey (North America)" },
    { value: "pilot", text: "Pilot" },
    { value: "stepwgn", text: "Stepwgn" },
    { value: "stream", text: "Stream" },
  ],
  hyndai: [
    { value: "elantra", text: "Elantra" },
    { value: "getz", text: "Getz" },
    { value: "grace", text: "Grace" },
    { value: "i40", text: "i40" },
    { value: "ix35", text: "ix35" },
    { value: "santa-fe", text: "Santa Fe" },
    { value: "solaris", text: "Solaris" },
    { value: "sonata", text: "Sonata" },
    { value: "starex-h-1", text: "Starex (H-1)" },
    { value: "tucson", text: "tucson" },
  ],
  kia: [
    { value: "carnival", text: "Carnival" },
    { value: "ceed", text: "Ceed" },
    { value: "cerato", text: "Cerato" },
    { value: "k5", text: "K5" },
    { value: "k7", text: "K7" },
    { value: "magentis", text: "Magentis" },
    { value: "morning", text: "Morning" },
    { value: "optima", text: "Optima" },
    { value: "picanto", text: "Picanto" },
    { value: "rio", text: "Rio" },
    { value: "sorento", text: "Sorento" },
    { value: "soul", text: "Soul" },
    { value: "sportage", text: "Sportage" },
  ],
  lexus: [
    { value: "es", text: "ES" },
    { value: "gs", text: "GS" },
    { value: "gx", text: "GX" },
    { value: "is", text: "IS" },
    { value: "ls", text: "LS" },
    { value: "lx", text: "LX" },
    { value: "nx", text: "NX" },
    { value: "rx", text: "RX" },
  ],
  mazda: [
    { value: "3", text: "3" },
    { value: "323", text: "323" },
    { value: "6", text: "6" },
    { value: "626", text: "626" },
    { value: "atenza", text: "Atenza" },
    { value: "cronos", text: "Cronos" },
    { value: "cx-5", text: "CX-5" },
    { value: "cx-7", text: "CX-7" },
    { value: "cx-9", text: "CX-9" },
    { value: "demio", text: "Demio" },
    { value: "familia", text: "Familia" },
    { value: "millenia", text: "Millenia" },
    { value: "mpv", text: "MPV" },
    { value: "premacy", text: "Premacy" },
    { value: "tribute", text: "Tribute" },
    { value: "xedos-6", text: "Xedos 6" },
    { value: "xedos-9", text: "Xedos 9" },
  ],
  mers: [
    { value: "a-class", text: "A-класс" },
    { value: "c-class", text: "C-класс" },
    { value: "cl-class", text: "CL-класс" },
    { value: "e-class", text: "E-класс" },
    { value: "e-class-amg", text: "E-класс AMG" },
    { value: "gl-class", text: "GL-класс" },
    { value: "gle", text: "GLE" },
    { value: "m-class", text: "M-класс" },
    { value: "s-class", text: "S-класс" },
    { value: "viano", text: "Viano" },
    { value: "vito", text: "Vito" },
    { value: "w123", text: "W123" },
    { value: "w124", text: "W124" },
  ],
  mitsubishi: [
    { value: "carisma", text: "Carisma" },
    { value: "colt", text: "Colt" },
    { value: "delica", text: "Delica" },
    { value: "eclipse", text: "Eclipse" },
    { value: "galant", text: "Galant" },
    { value: "l200", text: "L200" },
    { value: "lancer", text: "Lancer" },
    { value: "lancer-evolution", text: "Lancer Evolution" },
    { value: "montero", text: "Montero" },
    { value: "montero-sport", text: "Montero Sport" },
    { value: "outlander", text: "Outlander" },
    { value: "pajero", text: "Pajero" },
    { value: "pajero-sport", text: "Pajero Sport" },
  ],
  nissan: [
    { value: "almera-tion", text: "Almera Tino" },
    { value: "cefiro", text: "Cefiro" },
    { value: "juke", text: "Juke" },
    { value: "maxima", text: "Maxima" },
    { value: "Murano", text: "Murano" },
    { value: "navara-frontier", text: "Navara (Frontier)" },
    { value: "pathfinder", text: "Pathfinder" },
    { value: "patrol", text: "Patrol" },
    { value: "primera", text: "Primera" },
    { value: "qashqai", text: "Qashqai" },
    { value: "skyline", text: "Skyline" },
    { value: "teana", text: "Teana" },
    { value: "terrano", text: "Terrano" },
    { value: "xtrail", text: "X-Trail" },
  ],
  opel: [
    { value: "antara", text: "Antara" },
    { value: "astra", text: "Astra" },
    { value: "cors", text: "Corsa" },
    { value: "frontera", text: "Frontera" },
    { value: "insignia", text: "Insignia" },
    { value: "meriva", text: "Meriva" },
    { value: "omega", text: "Omega" },
    { value: "sintra", text: "Sintra" },
    { value: "vectra", text: "Vectra" },
    { value: "vivaro", text: "Vivaro" },
    { value: "zafira", text: "Zafira" },
  ],
  renault: [
    { value: "11", text: "11" },
    { value: "12", text: "12" },
    { value: "14", text: "14" },
    { value: "15", text: "15" },
    { value: "16", text: "16" },
    { value: "17", text: "17" },
    { value: "18", text: "18" },
    { value: "19", text: "19" },
    { value: "20", text: "20" },
    { value: "21", text: "21" },
    { value: "25", text: "25" },
    { value: "30", text: "30" },
    { value: "4", text: "4" },
    { value: "5", text: "5" },
    { value: "6", text: "6" },
    { value: "9", text: "9" },
    { value: "arkana", text: "Arkana" },
    { value: "avantime", text: "Avantime" },
    { value: "city-k-ze", text: "City K-ZE" },
    { value: "clio", text: "Clio" },
    { value: "clio-rs", text: "Clio RS" },
    { value: "clio-v6", text: "Clio V6" },
    { value: "dokker", text: "Dokker" },
    { value: "duster", text: "Duster" },
    { value: "espace", text: "Espace" },
    { value: "estafette", text: "Estafette" },
    { value: "fluence", text: "Fluence" },
    { value: "fuego", text: "Fuego" },
    { value: "kadjar", text: "Kadjar" },
    { value: "kangoo", text: "Kangoo" },
    { value: "kaptur", text: "Kaptur" },
    { value: "koleos", text: "Koleos" },
    { value: "kwid", text: "KWID" },
    { value: "laguna", text: "Laguna" },
    { value: "latitude", text: "Latitude" },
    { value: "lodgy", text: "Lodgy" },
    { value: "logan", text: "Logan" },
    { value: "megane", text: "Megane" },
    { value: "megane-e-tech", text: "Megane E-Tech" },
    { value: "megane-rs", text: "Megane RS" },
    { value: "modus", text: "Modus" },
    { value: "rodeo", text: "Rodeo" },
    { value: "safrane", text: "Safrane" },
    { value: "sandero", text: "Sandero" },
    { value: "sandero-rs", text: "Sandero RS" },
    { value: "scenic", text: "Scenic" },
    { value: "sport-spider", text: "Sport Spider" },
    { value: "symbol", text: "Symbol" },
    { value: "talisman", text: "Talisman" },
    { value: "trafic", text: "Trafic" },
    { value: "twingo", text: "Twingo" },
    { value: "twizy", text: "Twizy" },
    { value: "vel-satis", text: "Vel Satis" },
    { value: "wind", text: "Wind" },
    { value: "zoe", text: "ZOE" },
  ],
  subaru: [
    { value: "forester", text: "Forester" },
    { value: "impreza", text: "Impreza" },
    { value: "impreza-wrx", text: "Impreza WRX" },
    { value: "impreza-wrx-sti", text: "Impreza WRX STi" },
    { value: "legacy", text: "Legacy" },
    { value: "outback", text: "Outback" },
    { value: "tribeca", text: "Tribeca" },
    { value: "xv", text: "XV" },
  ],
  toyota: [
    { value: "4runner", text: "4Runner" },
    { value: "allex", text: "Allex" },
    { value: "allion", text: "Allion" },
    { value: "alphard", text: "Alphard" },
    { value: "altezza", text: "Altezza" },
    { value: "aristo", text: "Aristo" },
    { value: "auris", text: "Auris" },
    { value: "avalon", text: "Avalon" },
    { value: "avensis", text: "Avensis" },
    { value: "avensis-verso", text: "Avensis Verso" },
    { value: "c-hr", text: "C-HR" },
    { value: "caldina", text: "Caldina" },
    { value: "camry", text: "Camry" },
    { value: "camry-japan", text: "Camry (Japan)" },
    { value: "camry-solara", text: "Camry Solara" },
    { value: "carina", text: "Carina" },
    { value: "carina-ed", text: "Carina ED" },
    { value: "celica", text: "Celica" },
    { value: "corolla", text: "Corolla" },
    { value: "corolla-verso", text: "Corolla Verso" },
    { value: "crown", text: "Crown" },
    { value: "crown-majesta", text: "Crown Majesta" },
    { value: "fj-cruiser", text: "FJ Cruiser" },
    { value: "fortuner", text: "Fortuner" },
    { value: "funcargo", text: "FunCargo" },
    { value: "gaia", text: "Gaia" },
    { value: "harrier", text: "Harrier" },
    { value: "hiace", text: "HiAce" },
    { value: "highlander", text: "Highlander" },
    { value: "hilux", text: "Hilux" },
    { value: "hilux-surf", text: "Hilux Surf" },
    { value: "ipsum", text: "Ipsum" },
    { value: "ist", text: "Ist" },
    { value: "kluger", text: "Kluger" },
    { value: "land-cruiser", text: "Land Cruiser" },
    { value: "land-cruiser-prado", text: "Land Cruiser Prado" },
    { value: "mark-ii", text: "Mark II" },
    { value: "mark-x", text: "Mark X" },
    { value: "nadia", text: "Nadia" },
    { value: "noah", text: "Noah" },
    { value: "opa", text: "Opa" },
    { value: "previa", text: "Previa" },
    { value: "prius", text: "Prius" },
    { value: "prius-c", text: "Prius c" },
    { value: "prius-v", text: "Prius v (+)" },
    { value: "raum", text: "Raum" },
    { value: "rav4", text: "RAV4" },
    { value: "sequoia", text: "Sequoia" },
    { value: "sienna", text: "Sienna" },
    { value: "tundra", text: "Tundra" },
    { value: "urban-cruiser", text: "Urban Cruiser" },
    { value: "venza", text: "Venza" },
    { value: "verossa", text: "Verossa" },
    { value: "verso", text: "Verso" },
    { value: "vista", text: "Vista" },
    { value: "voltz", text: "Voltz" },
    { value: "voxy", text: "Voxy" },
    { value: "will", text: "WiLL" },
    { value: "will-cypha", text: "WiLL Cypha" },
    { value: "windom", text: "Windom" },
    { value: "wish", text: "Wish" },
    { value: "yaris", text: "Yaris" },
    { value: "yaris-verso", text: "Yaris Verso" },
  ],
  volkswagen: [
    { value: "", text: "Caravelle" },
    { value: "", text: "Golf" },
    { value: "", text: "Golf GTI" },
    { value: "", text: "Jetta" },
    { value: "", text: "Multivan" },
    { value: "", text: "Passat" },
    { value: "", text: "Passat CC" },
    { value: "", text: "Polo" },
    { value: "", text: "Sharan" },
    { value: "", text: "Tiguan" },
    { value: "", text: "Touareg" },
    { value: "", text: "Transporter" },
    { value: "", text: "Vento" },
  ],
};

const cities = [
  { value: "any", text: "Любой" },
  { value: "bishkek", text: "Бишкек" },
  { value: "osh", text: "Ош" },
];

$(document).ready(function () {
  $.each(brands, function (key, obj) {
    $("#brand").append(`<option value="${obj.value}">${obj.text}</option>`);
  });
  $("#brand").on("change", function () {
    const brand = this.value;
    if (brand in models) {
      $("#model")
        .empty()
        .attr("disabled", false)
        .append(`<option value="any">Любая модель</option>`);
      $.each(models[brand], function (key, obj) {
        $("#model").append(`<option value="${obj.value}">${obj.text}</option>`);
      });
    } else {
      $("#model")
        .empty()
        .attr("disabled", true)
        .append(`<option value="any">Любая модель</option>`);
    }
  });
  $("#model")
    .empty()
    .attr("disabled", true)
    .append(`<option value="any">Любая модель</option>`);
  $("#year").append(`<option value="any">Любой год</option>`);
  for (var i = 2023; i >= 1980; --i)
    $("#year").append(`<option value="${i}">${i}</option>`);

  $.each(cities, function (key, obj) {
    $("#city").append(`<option value="${obj.value}">${obj.text}</option>`);
  });

  $(".button-group").on("click", ".button", function () {
    $(this)
      .addClass("button-pressed")
      .siblings()
      .removeClass("button-pressed")
      .addClass("button-default");
  });
});
